name: blank

on: push

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sample build step
        run: echo "This is the build job"

